services:
  - type: web
    name: pulse-chat
    runtime: node
    plan: free
    buildCommand: NODE_ENV=development npm install && NODE_ENV=development npm --prefix frontend install && NODE_ENV=development npm --prefix frontend run build && NODE_ENV=development npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
